### ISSUE TITLE
Strange Git-Descriptor

### ISSUE THREAD

**Issue by juergen-albert** [eclipse/org.eclipse.sensinact.gateway#283]
Not sure where it comes from, but the bundle from the eclipse nexus with the latest Snapshot show a strange Git-Secriciptor: `Git-Descriptor                          Brain_IoT_All_In_One-977-g7ad4fa889-dirty`

This comes from the `org.eclipse.sensinact.gateway.southbound.mqtt.mqtt-client` version `0.0.2.202312011241`

**Comment by tcalmant** [comment]
The [root pom file](https://github.com/eclipse/org.eclipse.sensinact.gateway/blob/master/pom.xml#L512) uses `git describe --dirty --always --abbrev=9` to generate that entry, which returns last tag and adds "dirty" if git was updated since.

`Brain_IoT....` is the [latest tag](https://github.com/eclipse/org.eclipse.sensinact.gateway/tags), so it works as expected, but I agree we should check if that changes after the next release
