### ISSUE TITLE
replace org.eclipse.sensinact.gateway.core.geo-json with emf model

### ISSUE THREAD

**Issue by juergen-albert** [eclipse/org.eclipse.sensinact.gateway#402]
Right now, we use geojson Objects as a Datatype. It does the job, but beats the purpose. It would be great if we could replace it with a fitting EMF Model (we have a few flying around).

**Comment by timothyjward** [comment]
> It would be great if we could replace it with a fitting EMF Model

This would be fine for the admin service. I do think that we need a clean (i.e. EMF dependency free) GeoJSON object type to use elsewhere though, for example in events and in the REST API. We've worked hard to avoid EMF being a mandatory dependency everywhere so that "normal use" can be achieved in a minimal way.
